
browser=chrome
url=https://store-dev.globtech.in/
#SignUp Data
firstName=ashish
lastName=S
#Take Email Id from BM Manager
email=uahad@ymail.com
password=12345
confirmpassword=12345
phone=7894561212
country=United Arab Emirates
city=Ajman
pass=123456
#SignIn
signInEmail=asifbgd111@gmail.com
signInPassword=123456
#AdmissionNo
admissionNo=11182/25

